name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
env:
  go_version: ${{ vars.ARCALOT_GO_VERSION }}
jobs:
  lint_and_test:
    name: lint and test
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_lint_and_test.yaml@main
  build:
    name: build
    permissions:
      contents: write
    needs:
      - lint_and_test
    with:
      for_release: ${{ startsWith(github.event.ref, 'refs/tags/') }}
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_release.yaml@main
