name: Arcaflow Docsgen Python Plugin
on:
  workflow_call:
    inputs:
      plugin_path:
        required: true
        type: string

jobs:
  docsgen-python:
    name: Comparing ${{ github.ref_name }} docs from ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this project
        uses: actions/checkout@v4

      - name: Install arcaflow-docsgen
        env:
          DOCSGEN_VER: "0.4.1"
        run: |
          wget https://github.com/arcalot/arcaflow-docsgen/releases/download/v${{env.DOCSGEN_VER}}/arcaflow-docsgen_${{env.DOCSGEN_VER}}_linux_amd64.tar.gz \
          && tar -C /usr/local/bin -xzf arcaflow-docsgen_${{env.DOCSGEN_VER}}_linux_amd64.tar.gz

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.5

      - name: Install poetry
        run: |
          python -m pip install poetry==1.8.3

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Generate schema yaml
        run: |      
          python -m poetry run python ./${{ inputs.plugin_path }} --schema > schema.yaml
      
      - name: Create temp readme
        run: |
          cp README.md README_TMP.md

      - name: Run arcaflow-docsgen
        run: |
          python -m poetry run arcaflow-docsgen -markdown README_TMP.md -schema schema.yaml

      - name: Determine diff
        run: |
          echo "README_DIFF=$(cmp -s README.md README_TMP.md ; echo $?)" >> $GITHUB_ENV
      
      - name: Update README.md if appropriate
        # The github.head_ref variable is only available for pull requests,
        # however, we probably shouldn't be updating the branch for anything
        # which isn't a PR, anyway!
        if: env.README_DIFF == 1 && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: arcalot@redhat.com
          GH_USERNAME: arcabot
        run: |
          git config --global user.name $GH_USERNAME
          git config --global user.email $GH_EMAIL
          git fetch origin ${{ github.head_ref }}
          git checkout -f ${{ github.head_ref }}
          mv README_TMP.md README.md
          git commit -m 'Automatic update of README.md by arcaflow-docsgen arcabot' README.md
          git push origin HEAD:${{ github.head_ref }}
          git checkout -f refs/remotes/pull/${{ github.ref_name }}
