name: Arcaflow Docsgen Python Plugin
on:
  workflow_call:
    inputs:
      plugin_path:
        required: true
        type: string

jobs:
  docsgen-python:
    name: Comparing ${{ github.ref_name }} docs from ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this project
        uses: actions/checkout@v4

      - name: Install arcaflow-docsgen
        run: |
          wget https://github.com/arcalot/arcaflow-docsgen/releases/download/v0.1.1/arcaflow-docsgen_0.1.1_linux_amd64.tar.gz \
          && tar -C /usr/local/bin -xzf arcaflow-docsgen_0.1.0_linux_amd64.tar.gz

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.16

      - name: Install poetry
        run: |
          python -m pip install poetry==1.4.2

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Generate schema yaml
        run: |      
          python -m poetry run python ./${{ inputs.plugin_path }} --schema > schema.yaml
      
      - name: Create temp readme
        run: |
          cp README.md README_TMP.md

      - name: Run arcaflow-docsgen
        run: |
          python -m poetry run arcaflow-docsgen -markdown README_TMP.md -schema schema.yaml

      - name: Determine diff
        run: |
          set +e
          diff README.md README_TMP.md > arcaflow-docsgen.diff
          set -e
          echo "README_DIFF=$(cat arcaflow-docsgen.diff | wc -l)" >> $GITHUB_ENV
      
      - name: Update README.md if necessary
        if: env.README_DIFF != 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: arcalot@redhat.com
          GH_USERNAME: arcabot
        run: |
          mv README_TMP.md README.md
          git config --global user.name $GH_USERNAME
          git config --global user.email $GH_EMAIL
          git add README.md
          git commit -m 'Automatic upate of README.md by arcaflow-docsgen arcabot'
          git push
